In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import scipy

In [2]:
scipy.__version__

'1.1.0'

# `minimize()`

This is used to minimize a scalar function of 1 or more variables, and is what I will probably use in my neural network training code.

## Calling signature

`res = scipy.optimize.minimize(fun, x0, args=(), method=None, jac=None, hess=None, hessp=None, bounds=None, constraints=(), tol=None, callback=None, options=None)`

`f` is the function to minimize, called as `f(x,*args)->float`.

`x0` is the `ndarray` of the starting guess vector.

`args` is a tuple of additional arguments to the function (see above).

`method` is the method to use, one of: 'Nelder-Mead', 'Powell', 'CG', 'BFGS', 'Newton-CG', 'L-BFGS-B', 'TNC', 'COBYLA', 'SLSQP', 'trust-constr', 'dogleg', 'trust-ncg', 'trust-exact', 'trust-krylov', or a callable object. The default is `BFGS`, `L-BFGS-B`, or `SLSQP`, depending on whether or not the problem has constraints, or is bounded.

`jac` is a method for computing the gradient (Jacobian) vector. Only used for `CG`, `BFGS`, `Newton-CG`, `L-BFGS-B`, `TNC`, `SLSQP`, `dogleg`, `trust-ncg`, `trust-krylov`, `trust-exact`, `trust-constr`. Can also be a finite difference specifier for numerical gradient estimation: `2-point`, `3-point` (only for `trust-constr`), `cs` (ditto). If `jac` is `True`, the code assumes the objective function also returns the gradient. If `False`, `2-point` is used.

`hess` is a method for computing the Hessian (2nd partials) matrix. Only used by `Newton-CG`, `dogleg`, `trust-ncg`, `trust-krylov`, `trust-exact`, `trust-constr`. If callable, should return Hessian matrix (see docs). `2-point`, `3-point`, and `cs` can also be used for finite difference Hessian estimation for `trust-constr`. Or use a callable object that implements the `HessianUpdateStrategy` interface. If `jac` use finite differences, `hess` must use a quasi-Newton method (`BFGS` or `SR1`).

`hessp` is the Hessian times an arbitrary vector `p`, for `Newton-CG`, `trust-ncg`, `trust-krylov`, `trust-constr`. Only need one of `hess` or `hessp`; other is ignored.

`bounds` is a sequence of bounds on variables for `L-BFGS-B`, `TNC`, `SLSQP`, `trust-constr`. Can be a `Bounds` object, or a sequence of `(min,max)` pairs. Use `None` for no bounds.

`constraints` is a dictionary of constraints, or a list of dictionaries. Only used for `COBYLA`, `SLSQP`, `trust-constr`. See docs for details.

`tol` is the termination tolerance.

`options` is a dictionary of solver options, such as `maxiter` and `disp`.

`callback` is a function called after each iteration. For most methods, it is `callback(xk)` where `xk` is the current parameter vector. For `trust-constr`, it is `callback(xk, OptimizeResult state)->bool`.

*res* is an `OptimizeResult` object. The important attributes are: `x` - the solution array, `success` - a Boolean indicating a solution was found, and `message` - a string indicating the cause of the termination.

In [4]:
from scipy.optimize import minimize, rosen, rosen_der

In [5]:
x0 = [1.3, 0.7, 0.8, 1.9, 1.2]
res = minimize(rosen, x0, method='Nelder-Mead', tol=1e-6)
res.x

array([1.00000002, 1.00000002, 1.00000007, 1.00000015, 1.00000028])

In [6]:
res = minimize(rosen, x0, method='BFGS', jac=rosen_der, options={'gtol': 1e-6, 'disp': True})
res.x

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 26
         Function evaluations: 31
         Gradient evaluations: 31


array([1., 1., 1., 1., 1.])

In [7]:
dir(res)

['fun',
 'hess_inv',
 'jac',
 'message',
 'nfev',
 'nit',
 'njev',
 'status',
 'success',
 'x']

Now try some constraints.

In [12]:
fun = lambda x: (x[0] - 1)**2 + (x[1] - 2.5)**2
cons = ({'type':'ineq', 'fun': lambda x: x[0] - 2 * x[1] + 2},
        {'type':'ineq', 'fun': lambda x: -x[0] - 2 * x[1] + 6},
        {'type':'ineq', 'fun': lambda x: -x[0] + 2 * x[1] + 2})
bnds = ((0, None), (0, None))  # All positives
res = minimize(fun, (2,0), method='SLSQP', bounds=bnds, constraints=cons, options={'disp':True})
res.x

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.8000000011920985
            Iterations: 3
            Function evaluations: 13
            Gradient evaluations: 3


array([1.4, 1.7])